name: Run Discord Bot

on:
  workflow_dispatch:

jobs:
  clean-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py

      - name: Debug - List files
        run: ls -al

      - name: Run deletion script
        run: python bot.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          TARGET_CHANNEL_ID: ${{ secrets.TARGET_CHANNEL_ID }}
          TARGET_WEBHOOK_ID: ${{ secrets.TARGET_WEBHOOK_ID }}
          DELETE_THRESHOLD_MIN: ${{ secrets.DELETE_THRESHOLD_MIN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}  # ✅ Add this
