name: Run Discord Bot

on:
  workflow_dispatch:     # Allows manual run from GitHub

jobs:
  clean-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install discord.py
        run: pip install discord.py

      - name: Run deletion script
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          TARGET_CHANNEL_ID: ${{ secrets.TARGET_CHANNEL_ID }}
          TARGET_WEBHOOK_ID: ${{ secrets.TARGET_WEBHOOK_ID }}
          DELETE_THRESHOLD_MIN: ${{ secrets.DELETE_THRESHOLD_MIN }}
        run: python bot.py
